FROM assemblage-gcc:base

# RUN echo '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' >> /gtoken
# RUN gh auth login --with-token < /gtoken

ENV CC='gcc'
ENV CXX='g++'

RUN echo '1:gcc' >> /conf

WORKDIR /assemblage